# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20180303_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='tag',
        ),
    ]
