# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20180304_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
