# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 08:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
