# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 04:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
